package com.example.model

enum class LanguageCode {
    BANGLA, ENGLISH
}

object AppStrings {
    fun get(key: String, isBangla: Boolean): String {
        val bnMap = mapOf(
            "welcome_title" to "স্বাগতম!",
            "welcome_subtitle" to "সহজ মোবাইল রিচার্জ, এনক্রিপ্টেড পেমেন্ট ও কমিশন ওয়ালেট",
            "get_started" to "শুরু করুন",
            "app_title" to "পে-রিচার্জ ইন্ডিয়া",
            "main_balance" to "মূল ব্যালেন্স",
            "commission_balance" to "কমিশন ব্যালেন্স",
            "tap_to_view" to "ব্যালেন্স দেখতে ট্যাপ করুন",
            "quick_recharge" to "মোবাইল রিচার্জ",
            "bill_pay" to "বিল পে",
            "commission" to "কমিশন হিসাব",
            "history" to "লেনদেনের ইতিহাস",
            "support_chat" to "লাইভ সাপোর্ট",
            "dispute_tickets" to "অভিযোগ ও সমাধান",
            "security_vault" to "এনক্রিপশন ও সিকিউরিটি",
            "settings" to "সেটিংস",
            "operator" to "অপারেটর",
            "enter_number" to "মোবাইল নম্বর লিখুন",
            "amount" to "পরিমাণ (₹)",
            "enter_pin" to "৪-ডিজিটের ট্রানজ্যাকশন পিন লিখুন",
            "confirm_pay" to "নিশ্চিত ও পেমেন্ট করুন",
            "commission_earned" to "আপনি কমিশন পাবেন",
            "prepaid" to "প্রিপেইড",
            "postpaid" to "পোস্টপেইড",
            "skitto" to "স্কিটো",
            "electricity" to "বিদ্যুৎ বিল",
            "gas" to "গ্যাস বিল",
            "water" to "পানি বিল",
            "internet" to "ইন্টারনেট বিল",
            "dth" to "ডিটিএইচ টিভি",
            "meter_number" to "মিটার বা একাউন্ট নম্বর",
            "fetch_bill" to "বিল চেক করুন",
            "transaction_success" to "লেনদেন সফল হয়েছে!",
            "transaction_failed" to "লেনদেন ব্যর্থ হয়েছে",
            "receipt" to "ডিজিটাল রসিদ",
            "report_issue" to "অভিযোগ বা সমস্য জানান",
            "security_level" to "সিকিউরিটি লেভেল: সর্বোচ্চ (AES-256)",
            "biometric_auth" to "বায়োমেট্রিক ও পিন প্রটেকশন",
            "language" to "ভাষা (Language)",
            "dark_theme" to "ডার্ক মোড (Dark Mode)",
            "change_pin" to "পিন পরিবর্তন করুন",
            "transfer_commission" to "কমিশন মূল ব্যালেন্সে স্থানান্তর",
            "copy_txid" to "ট্রানজ্যাকশন আইডি কপি",
            "search_history" to "লেনদেন খুঁজুন...",
            "chat_placeholder" to "আপনার সমস্যা বা প্রশ্ন লিখুন...",
            "type_issue" to "সমস্যার ধরন নির্বাচন করুন",
            "ticket_open" to "ওপেন",
            "ticket_in_progress" to "চলমান",
            "ticket_resolved" to "সমাধানকৃত",
            "status" to "স্ট্যাটাস",
            "welcome_banner" to "WELLCOME TO PAYRECHARGE"
        )

        val enMap = mapOf(
            "welcome_title" to "WELCOME!",
            "welcome_subtitle" to "Fast Mobile Recharge, Encrypted Bill Payments & Commission Vault",
            "get_started" to "Get Started",
            "app_title" to "PayRecharge India",
            "main_balance" to "Main Balance",
            "commission_balance" to "Commission Balance",
            "tap_to_view" to "Tap to show balance",
            "quick_recharge" to "Mobile Recharge",
            "bill_pay" to "Bill Payment",
            "commission" to "Commission Wallet",
            "history" to "Transaction History",
            "support_chat" to "Live Support Chat",
            "dispute_tickets" to "Issue Resolution",
            "security_vault" to "Encryption & Security",
            "settings" to "Settings",
            "operator" to "Operator",
            "enter_number" to "Enter Mobile Number",
            "amount" to "Amount (₹)",
            "enter_pin" to "Enter 4-Digit Transaction PIN",
            "confirm_pay" to "Confirm & Pay",
            "commission_earned" to "Commission Earned",
            "prepaid" to "Prepaid",
            "postpaid" to "Postpaid",
            "skitto" to "Skitto",
            "electricity" to "Electricity",
            "gas" to "Gas Bill",
            "water" to "Water Bill",
            "internet" to "Internet",
            "dth" to "DTH TV",
            "meter_number" to "Account / Meter No",
            "fetch_bill" to "Check Bill Amount",
            "transaction_success" to "Transaction Successful!",
            "transaction_failed" to "Transaction Failed",
            "receipt" to "Digital Receipt",
            "report_issue" to "Report Issue / Dispute",
            "security_level" to "Security Level: Maximum (AES-256)",
            "biometric_auth" to "Biometric & PIN Protection",
            "language" to "Language",
            "dark_theme" to "Dark Theme",
            "change_pin" to "Change Transaction PIN",
            "transfer_commission" to "Transfer Commission to Main Wallet",
            "copy_txid" to "Copy Transaction ID",
            "search_history" to "Search transactions...",
            "chat_placeholder" to "Type your issue or query here...",
            "type_issue" to "Select Issue Category",
            "ticket_open" to "Open",
            "ticket_in_progress" to "In Progress",
            "ticket_resolved" to "Resolved",
            "status" to "Status",
            "welcome_banner" to "WELLCOME TO PAYRECHARGE"
        )

        val map = if (isBangla) bnMap else enMap
        return map[key] ?: enMap[key] ?: key
    }
}
